server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: cy-image-search-resnet

  datasource:
    # 本地 MySQL 宿主映射端口 3307，兼容 MySQL8+ 公钥检索
    url: jdbc:mysql://localhost:3306/cy_oc?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

milvus:
  host: localhost
  port: 19530
minio:
  endpoint: http://minio:9000
  access-key: minio
  secret-key: minio123
  bucket: images

flask:
  # 本地 Python 特征提取服务
  url: http://localhost:5000/extract

# 可选：MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志级别
logging:
  level:
    root: INFO
    app.image: DEBUG
